Декоративные элементы на главной странице
htmlacademy-htmlcss/1522011-sedona-32 pull request #9
Opened 2021-11-03 10:00 UTC by Diam1992

2021-11-03 10:42 UTC, baileys-li requested changes
У этого блока не совпадают размеры и по дефолту нет рамки у кнопки
![image](https://user-images.githubusercontent.com/47776594/140046445-ba45e8e8-678f-4dcf-bf60-8fbd8511a1a6.png)

2021-11-03 10:42 UTC, baileys-li commented on styles/styles.css
> +  background-color: black;
Не тот цвет

2021-11-03 10:42 UTC, baileys-li commented on index.html
> +          <img class="icon-wave" src="image/wave.svg" width="1200" height="57" alt="#">
Это декоративная штука. Её нужно в css

При том можно нарисовать средствами css, кстати, но не обязательно
1. Почитай на досуге про свойство [clip-path](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path).
2. Поиграйся с этим [генератором](https://bennettfeely.com/clippy/)
3. Глянь [демку](https://codepen.io/aLitovko/pen/eYWKmwW)

2021-11-03 10:42 UTC, baileys-li commented on index.html
>                </a>
У сердечка есть плашка с количеством которую можно уже стилизировать

2021-11-03 10:42 UTC, baileys-li commented on index.html
> +              <a class="button button-soc face-mail" href="https://www.facebook.com/htmlacademy">
иконки не полупрозрачные при ховере

2021-11-03 10:44 UTC, baileys-li commented
Так же полезно будет изучить технику векторного спрайта
1. https://www.youtube.com/watch?v=dPoRsolsCjA
2. https://web-standards.ru/articles/accessible-svg-icons/

Но сейчас это не горит, лучше проработать технику следующего блкоа

2021-11-04 12:11 UTC, Diam1992 reviewed
Не все сделано, что то, не получается

2021-11-04 17:02 UTC, merged

2021-11-04 17:02 UTC, baileys-li commented
@Diam1992 Ну тогда уже на созвоне с этим разберёмся